### ISSUE TITLE
`calculate_sensitivity` is slow with a norm-proj-data that is filled with 1

### ISSUE THREAD

**Issue by Robert-PrescientImaging** [UCL/STIR#1153] opened 2023-02-06 23:37 UTC
I am using STIR python for image reconstruction, specifically the `PoissonLogLikelihoodWithLinearModelForMeanAndProjData3DFloat​` objective function class. I am trying to utilize the GPU projectors for fast image reconstruction, see the following code snippet:

```
obj_func = stir.PoissonLogLikelihoodWithLinearModelForMeanAndProjData3DFloat()
obj_func.set_input_data(conf.input_data)
obj_func.set_projector_pair_sptr(stir.ProjectorByBinPairUsingParallelproj())
obj_func.set_up(conf.image)
```

The parallelproj GPU projectors can give me a full forward and backward projection in seconds when called directly. However, the above snippet leads to the following console output, which is slow (~10 minutes) in computing the sensitivity:

```
INFO: Using distributable_computation with 21 threads on 24 processors.
INFO: Creating parallelproj data-structures
INFO: done
INFO: Creating parallelproj data-structures
INFO: done
INFO: Computing sensitivity
INFO: Calling parallelproj forward
INFO: done
INFO: Starting loop with 21 threads
INFO: Thread 10/21 calculating segment_num: -31, view_num: 7
INFO: Thread 13/21 calculating segment_num: -31, view_num: 3
[...more OpenMP multithreading...]
```

I have confirmed that each of these threads, running via OpenMP, are utilizing the a parallelproj's back projector (GPU) for sensitivity computation for a single `ViewSegmentNumbers​` entry in the vector. This is all implemented in [distributable.cxx](https://github.com/UCL/STIR/blob/master/src/recon_buildblock/distributable.cxx#L427-L495).

I am wondering how I might speed this process up for a faster reconstruction algorithm that fully capitalizes on the parallelproj GPU projectors. A couple of ideas:

1. Implement a reconstruction algorithm, e.g., OSEM, in python that directly uses the projectors.
2. Create a new modified cpp objective function in STIR that overrides the `distributable_sensitivity_computation​` and `distributable_sensitivity_computation​` calls
3. Or is the distributed implementation incorrect/not optimized for parallelproj?

Any other input would be welcome.

**Comment by Robert-PrescientImaging** [comment] 2023-02-06 23:39
@gschramm or @KrisThielemans or @robbietuk (my personal account) are probably best equip to help address this. I can try to contribute a PR change but discussion is welcome.

**Comment by gschramm** [comment] 2023-02-07 00:17
Unfortunately, I don't know the details of the implementation of all the loops well enough to give a definite answer.
But I guess it is because in the calculation of the backprojection for the sens images, 
the "complete" backprojection is split up into ```num_segements * num_views``` "very small" chunks 
which potentially creates a lot of host-GPU transfer overhead.
@KrisThielemans is that the case?

**Comment by Robert-PrescientImaging** [comment] 2023-02-07 15:06
That looks correct for me. `distributable.cxx` breaks the projdata into unique `ViewSegmentNumbers`. 
https://github.com/UCL/STIR/blob/593c06909201419716398d699211614eedd93df1/src/recon_buildblock/distributable.cxx#L435-L438
This small data is then given to the projector, hence lots of small GPU transfers that may limits speed.


However, `BackProjectByBin does the same 
https://github.com/UCL/STIR/blob/593c06909201419716398d699211614eedd93df1/src/recon_buildblock/BackProjectorByBin.cxx#L186-L211

**Comment by gschramm** [comment] 2023-02-07 17:23
Hm. I think @KrisThielemans knows best why the behavior is so different when calling back projection directly vs the calculation of the sensitivity images.

**Comment by KrisThielemans** [comment] 2023-02-07 18:25
For both GPU projectors, the backprojection happens in one go of all of the data, see [here](https://github.com/UCL/STIR/blob/593c06909201419716398d699211614eedd93df1/src/recon_buildblock/Parallelproj_projector/BackProjectorByBinParallelproj.cxx#L138). The calls with `RelatedViewgrams` just copy some data
https://github.com/UCL/STIR/blob/593c06909201419716398d699211614eedd93df1/src/recon_buildblock/Parallelproj_projector/BackProjectorByBinParallelproj.cxx#L236. A similar strategy is used for the [forward projection](https://github.com/UCL/STIR/blob/593c06909201419716398d699211614eedd93df1/src/recon_buildblock/Parallelproj_projector/ForwardProjectorByBinParallelproj.cxx#L180)

So i think the issue is more likely related to subsets. Currently, the above code backprojects all of the `ProjDataInMemory`, even if most of it is zero. (`parallelproj` will presumably not do anything, but by then we've copied all of the data to the GPU already).

You can test this by setting the number of subsets to 1. I'd also expect that if you don't use an attenuation image (as bin normalisation), the sensitivty calculation (almost) scales with the number of subsets. But maybe not, if you quote 10 mins...

**Comment by gschramm** [comment] 2023-02-07 18:52
The parallelproj backprojector kernel indeed checks whether the value to be backprojected is not equal to 0  - see [here](https://github.com/gschramm/parallelproj/blob/d8145ad6f3cd43b0cb9753171fa96caff561cd7f/cuda/src/projector_kernels.cu#L129).  But as you say, I think there is significant overhead when transfering many small chuncks of data between host and GPU + there is some overhead everytime a set of kernels are launched.

**Comment by Robert-PrescientImaging** [comment] 2023-02-07 19:03
Apologies, the initial snippet was incorrect, I realized this after the normalization/subset comment. Running:
```
obj_func = stir.PoissonLogLikelihoodWithLinearModelForMeanAndProjData3DFloat()
obj_func.set_input_data(conf.input_data)
obj_func.set_projector_pair_sptr(stir.ProjectorByBinPairUsingParallelproj())
obj_func.set_up(conf.image)
```
results in fast (6second) sensitivity calculation. However, 
```
obj_func = stir.PoissonLogLikelihoodWithLinearModelForMeanAndProjData3DFloat()
obj_func.set_input_data(conf.input_data)
obj_func.set_normalisation_sptr(stir.BinNormalisationFromProjData(conf.mult_factors))
obj_func.set_projector_pair_sptr(stir.ProjectorByBinPairUsingParallelproj())
obj_func.set_up(conf.image)
```
is taking 10 minutes to compute the sensitivities with the setting of the `normalisation_sptr`. For now, `conf.mult_factors` are uniform ones but in future will be attenuation.

P.S. `num_subsets=1` and this behaviour is independent of `use_subset_sensitivities = True` or `False`

**Comment by KrisThielemans** [comment] 2023-02-07 19:04
clarification: we do not call parallelproj in small chunks. Always the full data.

it seems somewhat non-trivial to figure which bits of the various arrays we'd need to transfer (without making extra CPU copies).

I think the only way that can be resolved is by reorganising quite a lot of STIR (well, distributable_computation mostly) to work by subset. Sadly, that's bad for OPENMP (that could probably be resolved without too much work) and even worse for MPI. @ashgillman's work to construct subset projection data was a work-around for that, usable from SIRF/STIR python (i.e. first construct a subset of the data, then forward/backproject all of that). That seems to need far more thought.

**Comment by KrisThielemans** [comment] 2023-02-07 20:03
@Robert-PrescientImaging that's pretty weird. I'm assuming you don't seem the same with `ProjMatrixByBinUsingRayTracing`? Someone (me?) will have to dig more into the code then.

@markus-jehl I guess you haven't seen this?

**Comment by Robert-PrescientImaging** [comment] 2023-02-07 21:48
> I'm assuming you don't seem the same with `ProjMatrixByBinUsingRayTracing`?

I believe this is what you mean:
```
obj_func = stir.PoissonLogLikelihoodWithLinearModelForMeanAndProjData3DFloat()
obj_func.set_input_data(conf.input_data)
obj_func.set_normalisation_sptr(stir.BinNormalisationFromProjData(conf.mult_factors))
projector_pair = stir.ProjectorByBinPairUsingProjMatrixByBin()
projector_pair.set_proj_matrix_sptr(stir.ProjMatrixByBinUsingRayTracing())
projector_pair.get_proj_matrix_ptr().enable_cache(False)
obj_func.set_projector_pair_sptr(projector_pair)
obj_func.set_use_subset_sensitivities(False)
obj_func.set_up(im)
```

Here is a timing comparison table. t0 is before `obj_func.set_up(im)` and t1 after. These are slightly different timings to aforementioned because I rebuilt STIR in RelWithDebInfo
|          | ParallelProj | RayTracing |
|----------|--------------|------------|
| w norm   | 298.2 sec    | 296.7 sec  |
| w/o norm | 12.2 sec     | 34.5 sec   |

So the inclusion of `obj_func.set_normalisation_sptr(stir.BinNormalisationFromProjData(conf.mult_factors))` equally negatively affects sensitivity calculation, regardless of projectors.

**Comment by KrisThielemans** [comment] 2023-02-08 07:52
I'm assuming that `config.mult_factors` is  a `ProjDataInterfile` or so. Can you try again with `ProjDataInMemory`? Also, can you report timings for just doing a `normalisation.undo()`? 

What timings are you reporting? CPU or wall-clock? It could also be good to do this with lower number of threads `stir.set_num_threads` I think)

Probably this is because we need to guard stream access. However, there are currently too many critical sections in the code, as originally I guarded at higher level (e.g. in [BinNormalisation](https://github.com/UCL/STIR/blob/a4b9269e95e5b37cf639d2808a4e40966155acdb/src/recon_buildblock/BinNormalisation.cxx#L161) and again [distributable](https://github.com/UCL/STIR/blob/a4b9269e95e5b37cf639d2808a4e40966155acdb/src/recon_buildblock/distributable.cxx#L221)) but then gave up and guarded in the stream access itself (e.g  [ProjDataFromStream](https://github.com/UCL/STIR/blob/a4b9269e95e5b37cf639d2808a4e40966155acdb/src/buildblock/ProjDataFromStream.cxx#L141)). It could be this makes mult-threading sit around waiting for a long time. The difficulty of course is that removing those superfluous critical sections is a bit scary, as you need to be sure that the underlying code is thread-safe (with all possibly `ProjData`  and `BinNormalisation` classes), and I don't know of any way to test that reliably.


You

**Comment by markus-jehl** [comment] 2023-02-08 15:47
Funnily I ran into (I suspect) exactly the same issue today: if the multiplicative factors are homogeneous, setting up the system matrix takes forever (in my case ~30 minutes). If I set it to something reasonable, the computation time goes down to around 3 minutes.

I have a vague memory running into this in python as well in the past, and back then I just added some small random noise to the homogeneous multiplicative factors when I didn't have a normalisation or attenuation correction to apply.

**Comment by KrisThielemans** [comment] 2023-02-08 15:57
I vaguely remember you telling me this. It's very weird!

**Comment by Robert-PrescientImaging** [comment] 2023-02-08 16:01
>I'm assuming that config.mult_factors is a ProjDataInterfile or so. Can you try again with ProjDataInMemory?

`config.mult_factors` is a shared_ptr to a `ProjDataInMemory` object. I am modifying the code to ensure that `config.input_data` is also `ProjDataInMemory`. Retesting the timings, as above, leads to the same results as above.

> It could also be good to do this with lower number of threads stir.set_num_threads I think)

with `stir.set_num_threads(1)` preceding the aforementioned function the timings are the following 

|          | ParallelProj | RayTracing |
|----------|--------------|------------|
| w norm   | 518.3 sec (2x)   | 610.8 sec (2x)  |
| w/o norm | 12.4 sec  (no change)   | 106.1 sec (3x) |
________



>Also, can you report timings for just doing a normalisation.undo()?

Not easily from python. The argument is `RelatedViewgrams`, which requires `DataSymmetriesForViewSegmentNumbers` etc that is not (correctly?) exposed to python. I get this error:

```
stir.DataSymmetriesForViewSegmentNumbers()
Traceback (most recent call last):
  File "/home/robert/pycharm/pycharm-community-2022.3.1/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
TypeError: Cannot create new instances of type 'stir.DataSymmetriesForViewSegmentNumbers'
```

________
The timings are reported from:
> import time
>     t0 = time.time()
>     obj_func.set_up(im)
>     t1 = time.time()
>     print("Time to set up obj_func: ", t1 - t0)
>     return t1 - t0

I am working on getting my C++ debugger working with WSL2.

________

>Probably this is because we need to guard stream access. However, there are currently too many critical sections in the code, as originally I guarded at higher level (e.g. in [BinNormalisation](https://github.com/UCL/STIR/blob/a4b9269e95e5b37cf639d2808a4e40966155acdb/src/recon_buildblock/BinNormalisation.cxx#L161) and again [distributable](https://github.com/UCL/STIR/blob/a4b9269e95e5b37cf639d2808a4e40966155acdb/src/recon_buildblock/distributable.cxx#L221)) but then gave up and guarded in the stream access itself (e.g [ProjDataFromStream](https://github.com/UCL/STIR/blob/a4b9269e95e5b37cf639d2808a4e40966155acdb/src/buildblock/ProjDataFromStream.cxx#L141)). It could be this makes mult-threading sit around waiting for a long time. The difficulty of course is that removing those superfluous critical sections is a bit scary, as you need to be sure that the underlying code is thread-safe (with all possibly ProjData and BinNormalisation classes), and I don't know of any way to test that reliably.

Does this apply if reading from memory?

**Comment by KrisThielemans** [comment] 2023-02-08 16:29
> `config.mult_factors` is a shared_ptr to a `ProjDataInMemory` object. I am modifying the code to ensure that `config.input_data` is also `ProjDataInMemory`. Retesting the timings, as above, leads to the same results as above.
>
the sensitivity computation doesn't use `conf.input_data` (aside from the "template info"), so timings won't change.
 
> > Also, can you report timings for just doing a normalisation.undo()?
> 
> Not easily from python. The argument is `RelatedViewgrams`, which requires `DataSymmetriesForViewSegmentNumbers` etc 

not sure why you get the error with   `DataSymmetriesForViewSegmentNumbers`, but there should be an overload that takes a `ProjData`. no?

> The timings are reported from:
> 
> > import time
> > t0 = time.time()

https://docs.python.org/3/library/time.html says `time.time()` returns "seconds since epoch".  `time.perf_counter()` would give you a bit higher precision, but that doesn't matter here. I'd be interested in seeing `time.process_time()` results.
> 
> > Probably this is because we need to guard stream access. 
> Does this apply if reading from memory?

`ProjDataInMemory` is currently derived from `ProjDataFromStream`, so yes. It could be rewritten to skip the stream interface and hence be faster. That doesn't mean it's easy to have it thread-safe of course. It's not so obvious to write code where you don't know if someone is going to write and someone else is going to read. It'd presumably be possibly to have thread-safe read-only access (which is all that's needed). Contributions welcome :-).

**Comment by Robert-PrescientImaging** [comment] 2023-02-08 19:49
> Funnily I ran into (I suspect) exactly the same issue today: if the multiplicative factors are homogeneous, setting up the system matrix takes forever (in my case ~30 minutes). If I set it to something reasonable, the computation time goes down to around 3 minutes.

I find this as well. Pre-re-running the timing tests I add some noisy to my uniform ones `config.mult_factors` with:
```
config.mult_factors.fill(1)
noise_generator = stir.GeneralisedPoissonNoiseGenerator(10000, True)
noisy_mult_factors = stir.ProjDataInMemory(config.mult_factors.get_exam_info(), config.mult_factors.get_proj_data_info())
noise_generator.generate_random(noisy_mult_factors , config.mult_factors)
config.mult_factors = noisy_mult_factors
```
and get timing results that indicate no impact by the use of normalization

|          | ParallelProj | RayTracing |
|----------|--------------|------------|
| w norm   | 12.8 sec   | 32.4 sec |
| w/o norm | 12.7 sec   | 32.9 sec |

**Comment by KrisThielemans** [comment] 2023-02-08 20:29
😮 

so, you're saying that if you just do
```python
config.mult_factors =  stir.ProjDataInMemory(config.input_data.get_exam_info(), config.input_data.get_proj_data_info())
config.mult_factors.fill(1)
```
everything slows down? Please try with `fill(2)`.

The only reason I can see is this check:
https://github.com/UCL/STIR/blob/a4b9269e95e5b37cf639d2808a4e40966155acdb/src/recon_buildblock/distributable.cxx#L215. The implementation of `is_trivial` is in this case
https://github.com/UCL/STIR/blob/master/src/recon_buildblock/BinNormalisationFromProjData.cxx#L117-L136
If we filled with 1, it's going to go through all of the data to decide it was trivial. And it's going to do this for all related_viewgrams. Moreover, all the `get_viewgrams` will have a critical section. If you have some random data, or 2, that loop will exit immediately.

If so, this would be easy to resolve presumably by storing a `bool` such that it's only gone through once.

**Comment by Robert-PrescientImaging** [comment] 2023-02-08 20:48
> everything slows down? Please try with fill(2).

Parallelproj setup in ~12 seconds and RayTracing in ~30 seconds.

It appears it is the[`!normalisation_sptr->is_trivial()` loop](https://github.com/UCL/STIR/blob/master/src/recon_buildblock/BinNormalisationFromProjData.cxx#L117-L136)

I shall make a PR that sets a member variable`_is_trivial = true` at the end of the loop, defaults to `false` and can be run with setup?

**Comment by KrisThielemans** [comment] 2023-02-08 22:38
It's a little bit tricky. I am somewhat hesitant to do this in set_up as it would give an overhead if people never call is_trivial. I was therefore thinking to have a mutable variable that would be set in the first call to is_trivial. To make that thread-safe but fast requires some trickery with a double lock (as used in ProjDataInfo).

However, I wonder if this isn't overkill. Who is ever going to set the  projdata all to 1 anyway, except for testing. In real life, is_trivial will always be false.

I therefore propose to cut out the loop and always return false. Easy code, fastest in real life, and apparently little overhead if it happens to be 1 anyway.

**Comment by Robert-PrescientImaging** [comment] 2023-02-08 22:47
Rather than cutting the loop from BinNormalisationFromProjData, couldn't we simply remove the `!normalisation_sptr->is_trivial()` call from?
https://github.com/UCL/STIR/blob/a4b9269e95e5b37cf639d2808a4e40966155acdb/src/recon_buildblock/distributable.cxx#L215
Initial testing fixes this issue.

**Comment by KrisThielemans** [comment] 2023-02-09 08:00
> Rather than cutting the loop from BinNormalisationFromProjData, couldn't we simply remove the `!normalisation_sptr->is_trivial()` call

We could, but that means calling `is_trivial` somewhere else will potentially have the same problem. In OO programming, it's always better to solve problems at source. I've created #1158 instead. @Robert-PrescientImaging @markus-jehl  please check if you can.

**Comment by markus-jehl** [comment] 2023-02-10 16:37
Sorry for the delay - these changes fix the issue!

**Closed** 2023-02-10 16:52 UTC
