### ISSUE TITLE
Lmtoprojdata image duration dpends on time frame definitions

### ISSUE THREAD

**Issue by danieldeidda** [UCL/STIR#1512] opened 2024-09-13 16:10 UTC
When creating the exam info LMtoProjdata get the examinfo from the LM but then set timeframe according to  time frame definitions, so if this was not set in the parfile we will have a time duration of 0 even though the LM exam info had a value>0

https://github.com/UCL/STIR/blob/6417022e54a4814f25776bc8ca1df3acd4e865f6/src/listmode_buildblock/LmToProjData.cxx#L661-L665

or maybe I am missing something

**Comment by KrisThielemans** [comment] 2024-09-23 14:24
Higher up in the `set_up()` there is
https://github.com/UCL/STIR/blob/6417022e54a4814f25776bc8ca1df3acd4e865f6/src/listmode_buildblock/LmToProjData.cxx#L426C7-L429
`all_frames_exam_info_sptr` is actually never used however. Presumably this should have been passed to the `post_normalisation_sptr->set_up()`

**Comment by KrisThielemans** [comment] 2024-09-23 14:29
We currently initialise `frame_defs` in `set_up`
https://github.com/UCL/STIR/blob/6417022e54a4814f25776bc8ca1df3acd4e865f6/src/listmode_buildblock/LmToProjData.cxx#L437-L447
This should at least be modified to `lm_data_ptr->get_exam_info_sptr()->get_time_frame_defs()` if `num_events_to_store` is zero. (And write a warning otherwise).

**Comment by KrisThielemans** [comment] 2024-09-23 14:33
Duplicate of #657.

Related to problems with time frames is #161

**Closed** 2024-11-19 17:20 UTC
